#!/usr/bin/env bash
# MINC - Defensive host<->VM communication guard for Kali hardening suite.
# Purpose: install reversible, least-privilege network policy for a Kali guest
# communicating with a known host. This is defensive isolation, not evasion.

set -euo pipefail

CONF_FILE="${CONF_FILE:-/etc/host_vm_comm_guard.conf}"
NFT_FILE="${NFT_FILE:-/etc/nftables.d/host_vm_comm_guard.nft}"
LOG_FILE="${LOG_FILE:-/var/log/host_vm_comm_guard.log}"
STATE_DIR="${STATE_DIR:-/var/lib/host_vm_comm_guard}"

DEFAULT_ALLOWED_TCP="22,5986"
DEFAULT_ALLOWED_UDP="51820"

log() {
    local msg="$1"
    mkdir -p "$(dirname "$LOG_FILE")"
    printf '%s host_vm_comm_guard: %s\n' "$(date -Is)" "$msg" | tee -a "$LOG_FILE" >/dev/null
}

fail() {
    log "ERROR: $1"
    echo "ERROR: $1" >&2
    exit 1
}

require_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        fail "run as root"
    fi
}

valid_ip_or_cidr() {
    local value="$1"
    [[ "$value" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$ ]] || return 1
    local ip="${value%%/*}"
    local cidr=""
    [[ "$value" == */* ]] && cidr="${value##*/}"
    IFS='.' read -r a b c d <<< "$ip"
    for octet in "$a" "$b" "$c" "$d"; do
        [[ "$octet" =~ ^[0-9]+$ ]] || return 1
        (( octet >= 0 && octet <= 255 )) || return 1
    done
    if [[ -n "$cidr" ]]; then
        [[ "$cidr" =~ ^[0-9]+$ ]] || return 1
        (( cidr >= 0 && cidr <= 32 )) || return 1
    fi
}

valid_ports_csv() {
    local csv="$1"
    [[ "$csv" =~ ^[0-9]+(,[0-9]+)*$ ]] || return 1
    IFS=',' read -ra ports <<< "$csv"
    local p
    for p in "${ports[@]}"; do
        (( p >= 1 && p <= 65535 )) || return 1
    done
}

write_default_config() {
    if [[ -f "$CONF_FILE" ]]; then
        return 0
    fi
    mkdir -p "$(dirname "$CONF_FILE")"
    cat > "$CONF_FILE" <<'CFG'
# host_vm_comm_guard configuration
# Set HOST_VM_HOST_CIDR to the host-side IP address or management subnet.
# Examples: 192.168.56.1/32 for VirtualBox host-only, 172.16.246.1/32 for VMware vmnet,
# or a narrow /30-/29 lab segment when the hypervisor uses a small NAT pool.
HOST_VM_HOST_CIDR="192.168.56.1/32"

# Keep this narrow. TCP 22 is SSH. TCP 5986 is WinRM over TLS.
HOST_VM_ALLOWED_TCP="22,5986"

# UDP 51820 is WireGuard. Leave empty if WireGuard is not used.
HOST_VM_ALLOWED_UDP="51820"

# If set to 1, keep non-host outbound traffic permitted and only isolate management ports.
# If set to 0, default-deny outbound except DNS/DHCP/established plus host management ports.
HOST_VM_PERMISSIVE_OUTBOUND="1"
CFG
    chmod 0640 "$CONF_FILE"
}

load_config() {
    write_default_config
    # shellcheck source=/dev/null
    source "$CONF_FILE"
    HOST_VM_HOST_CIDR="${HOST_VM_HOST_CIDR:-192.168.56.1/32}"
    HOST_VM_ALLOWED_TCP="${HOST_VM_ALLOWED_TCP:-$DEFAULT_ALLOWED_TCP}"
    HOST_VM_ALLOWED_UDP="${HOST_VM_ALLOWED_UDP:-$DEFAULT_ALLOWED_UDP}"
    HOST_VM_PERMISSIVE_OUTBOUND="${HOST_VM_PERMISSIVE_OUTBOUND:-1}"

    valid_ip_or_cidr "$HOST_VM_HOST_CIDR" || fail "invalid HOST_VM_HOST_CIDR: $HOST_VM_HOST_CIDR"
    [[ -z "$HOST_VM_ALLOWED_TCP" ]] || valid_ports_csv "$HOST_VM_ALLOWED_TCP" || fail "invalid HOST_VM_ALLOWED_TCP"
    [[ -z "$HOST_VM_ALLOWED_UDP" ]] || valid_ports_csv "$HOST_VM_ALLOWED_UDP" || fail "invalid HOST_VM_ALLOWED_UDP"
    [[ "$HOST_VM_PERMISSIVE_OUTBOUND" =~ ^[01]$ ]] || fail "HOST_VM_PERMISSIVE_OUTBOUND must be 0 or 1"
}

csv_to_nft_set() {
    local csv="$1"
    if [[ -z "$csv" ]]; then
        printf '{}'
        return 0
    fi
    printf '{ %s }' "${csv//,/ , }"
}

write_nft_policy() {
    mkdir -p "$(dirname "$NFT_FILE")" "$STATE_DIR"
    local tcp_set udp_set outbound_policy
    tcp_set="$(csv_to_nft_set "$HOST_VM_ALLOWED_TCP")"
    udp_set="$(csv_to_nft_set "$HOST_VM_ALLOWED_UDP")"
    outbound_policy="accept"
    [[ "$HOST_VM_PERMISSIVE_OUTBOUND" == "0" ]] && outbound_policy="drop"

    cat > "$NFT_FILE" <<NFT
#!/usr/sbin/nft -f
# Generated by host_vm_comm_guard.sh. Edit $CONF_FILE, not this file.

table inet host_vm_comm_guard {
    chain input {
        type filter hook input priority -5; policy accept;
        ct state established,related accept
        iifname "lo" accept
        ip saddr $HOST_VM_HOST_CIDR tcp dport $tcp_set accept
        ip saddr $HOST_VM_HOST_CIDR udp dport $udp_set accept
        tcp dport $tcp_set log prefix "host-vm-deny-in-tcp " flags all counter drop
        udp dport $udp_set log prefix "host-vm-deny-in-udp " flags all counter drop
    }

    chain output {
        type filter hook output priority -5; policy $outbound_policy;
        ct state established,related accept
        oifname "lo" accept
        udp dport { 53, 67, 68, 123 } accept
        tcp dport { 53, 80, 443 } accept
        ip daddr $HOST_VM_HOST_CIDR tcp dport $tcp_set accept
        ip daddr $HOST_VM_HOST_CIDR udp dport $udp_set accept
        ip daddr $HOST_VM_HOST_CIDR log prefix "host-vm-deny-out " flags all counter drop
    }
}
NFT
    chmod 0640 "$NFT_FILE"
}

install_nftables_include() {
    apt-get update -y >/dev/null 2>&1 || true
    DEBIAN_FRONTEND=noninteractive apt-get install -y nftables >/dev/null 2>&1 || true
    mkdir -p /etc/nftables.d
    if [[ -f /etc/nftables.conf ]] && ! grep -q 'include "/etc/nftables.d/\*.nft"' /etc/nftables.conf; then
        cp /etc/nftables.conf "$STATE_DIR/nftables.conf.backup.$(date +%s)"
        printf '\ninclude "/etc/nftables.d/*.nft"\n' >> /etc/nftables.conf
    elif [[ ! -f /etc/nftables.conf ]]; then
        printf '#!/usr/sbin/nft -f\nflush ruleset\ninclude "/etc/nftables.d/*.nft"\n' > /etc/nftables.conf
    fi
}

apply_policy() {
    install_nftables_include
    write_nft_policy
    nft -c -f "$NFT_FILE" || fail "nftables syntax check failed"
    nft -f "$NFT_FILE" || fail "failed to apply nftables policy"
    systemctl enable --now nftables >/dev/null 2>&1 || true
    log "applied policy for host $HOST_VM_HOST_CIDR tcp=$HOST_VM_ALLOWED_TCP udp=$HOST_VM_ALLOWED_UDP permissive_outbound=$HOST_VM_PERMISSIVE_OUTBOUND"
}

remove_policy() {
    if command -v nft >/dev/null 2>&1; then
        nft delete table inet host_vm_comm_guard >/dev/null 2>&1 || true
    fi
    rm -f "$NFT_FILE"
    log "removed active host_vm_comm_guard nftables table and policy file"
}

status_policy() {
    load_config
    echo "Config: $CONF_FILE"
    echo "Host CIDR: $HOST_VM_HOST_CIDR"
    echo "Allowed TCP: $HOST_VM_ALLOWED_TCP"
    echo "Allowed UDP: $HOST_VM_ALLOWED_UDP"
    echo "Permissive outbound: $HOST_VM_PERMISSIVE_OUTBOUND"
    if command -v nft >/dev/null 2>&1 && nft list table inet host_vm_comm_guard >/dev/null 2>&1; then
        echo "Policy: active"
    else
        echo "Policy: inactive"
    fi
}

usage() {
    cat <<USAGE
Usage: $0 <apply|remove|status|check>

apply   Create default config if missing, validate it, and apply nftables policy.
remove  Remove the guard table and generated policy file.
status  Print current configuration and active/inactive state.
check   Validate config and generated nftables syntax without applying rules.
USAGE
}

main() {
    local action="${1:-status}"
    case "$action" in
        apply)
            require_root
            load_config
            apply_policy
            ;;
        remove)
            require_root
            remove_policy
            ;;
        status)
            status_policy
            ;;
        check)
            require_root
            load_config
            install_nftables_include
            write_nft_policy
            nft -c -f "$NFT_FILE"
            log "configuration and nftables syntax validated"
            ;;
        -h|--help|help)
            usage
            ;;
        *)
            usage >&2
            exit 2
            ;;
    esac
}

main "$@"
