#!/usr/bin/env python3
# MINC - Tests for passive firstboot release-gate handoff summary smoke checks.
# Defensive validation only: no host, VM, service, firewall, model, dataset, or firstboot state is changed.

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


def write_summary(path: Path, overrides: dict[str, str] | None = None) -> None:
    values = {
        'FIRSTBOOT_HANDOFF_FRESHNESS_COMPONENT': 'firstboot_release_gate_handoff_freshness',
        'FIRSTBOOT_HANDOFF_FRESHNESS_CREATED_UTC': '2026-06-28T08:00:00Z',
        'FIRSTBOOT_HANDOFF_FRESHNESS_OK': '1',
        'FIRSTBOOT_HANDOFF_FRESHNESS_DECISION': 'approved',
        'FIRSTBOOT_HANDOFF_FRESHNESS_RELEASE_GATE': 'pass',
        'FIRSTBOOT_HANDOFF_FRESHNESS_INPUT': '/var/log/firstboot_release_gate.handoff_verify.json',
        'FIRSTBOOT_HANDOFF_FRESHNESS_MAX_AGE_MINUTES': '240',
        'FIRSTBOOT_HANDOFF_FRESHNESS_TOTAL_ARTIFACTS': '4',
        'FIRSTBOOT_HANDOFF_FRESHNESS_REQUIRED_VERIFIED': '4',
        'FIRSTBOOT_HANDOFF_FRESHNESS_FRESH_REQUIRED_VERIFIED': '4',
        'FIRSTBOOT_HANDOFF_FRESHNESS_VERIFICATION_EXISTS': '1',
        'FIRSTBOOT_HANDOFF_FRESHNESS_VERIFICATION_FRESH': '1',
        'FIRSTBOOT_HANDOFF_FRESHNESS_BLOCKER_COUNT': '0',
        'FIRSTBOOT_HANDOFF_FRESHNESS_BLOCKERS': 'none',
        'FIRSTBOOT_HANDOFF_FRESHNESS_PRIVACY_SCOPE': 'aggregate_release_gate_handoff_freshness_only',
    }
    if overrides:
        values.update(overrides)
    lines = [
        '# Generated by firstboot_release_gate_handoff_freshness.py',
        '# Aggregate freshness evidence only; no raw telemetry, credentials, captures, datasets, or identities.',
    ]
    lines.extend(f"{key}='{value}'" for key, value in values.items())
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def test_summary_smoke_accepts_passing_aggregate_summary(tmp_path: Path) -> None:
    summary = tmp_path / 'freshness.summary.env'
    output = tmp_path / 'summary_smoke.json'
    write_summary(summary)

    subprocess.run(
        [
            sys.executable,
            'firstboot_release_gate_handoff_summary_smoke.py',
            '--input',
            str(summary),
            '--output',
            str(output),
            '--require-pass',
        ],
        check=True,
        capture_output=True,
        text=True,
    )

    payload = json.loads(output.read_text(encoding='utf-8'))
    assert payload['component'] == 'firstboot_release_gate_handoff_summary_smoke'
    assert payload['ok'] is True
    assert payload['release_gate'] == 'pass'
    assert payload['source_values']['fresh_required_verified'] == 4
    assert payload['privacy_scope'] == 'aggregate_release_gate_handoff_summary_smoke_only'


def test_summary_smoke_fails_closed_on_contradictory_summary(tmp_path: Path) -> None:
    summary = tmp_path / 'freshness.summary.env'
    output = tmp_path / 'summary_smoke.json'
    write_summary(
        summary,
        {
            'FIRSTBOOT_HANDOFF_FRESHNESS_OK': '1',
            'FIRSTBOOT_HANDOFF_FRESHNESS_DECISION': 'deferred',
            'FIRSTBOOT_HANDOFF_FRESHNESS_RELEASE_GATE': 'stop',
        },
    )

    completed = subprocess.run(
        [
            sys.executable,
            'firstboot_release_gate_handoff_summary_smoke.py',
            '--input',
            str(summary),
            '--output',
            str(output),
            '--require-pass',
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    payload = json.loads(output.read_text(encoding='utf-8'))
    assert completed.returncode == 10
    assert payload['ok'] is False
    assert payload['release_gate'] == 'stop'
    assert 'ok_decision_mismatch' in payload['blockers']
    assert 'ok_release_gate_mismatch' in payload['blockers']


def test_summary_smoke_fails_closed_on_missing_required_key(tmp_path: Path) -> None:
    summary = tmp_path / 'freshness.summary.env'
    output = tmp_path / 'summary_smoke.json'
    write_summary(summary)
    text = summary.read_text(encoding='utf-8').replace(
        "FIRSTBOOT_HANDOFF_FRESHNESS_PRIVACY_SCOPE='aggregate_release_gate_handoff_freshness_only'\n",
        '',
    )
    summary.write_text(text, encoding='utf-8')

    completed = subprocess.run(
        [
            sys.executable,
            'firstboot_release_gate_handoff_summary_smoke.py',
            '--input',
            str(summary),
            '--output',
            str(output),
            '--require-pass',
        ],
        check=False,
        capture_output=True,
        text=True,
    )

    payload = json.loads(output.read_text(encoding='utf-8'))
    assert completed.returncode == 10
    assert 'missing_required_key:FIRSTBOOT_HANDOFF_FRESHNESS_PRIVACY_SCOPE' in payload['blockers']


def test_summary_smoke_markdown_documents_status_privacy_and_rollback(tmp_path: Path) -> None:
    summary = tmp_path / 'freshness.summary.env'
    output = tmp_path / 'summary_smoke.md'
    write_summary(summary)

    subprocess.run(
        [
            sys.executable,
            'firstboot_release_gate_handoff_summary_smoke.py',
            '--input',
            str(summary),
            '--output',
            str(output),
            '--format',
            'markdown',
        ],
        check=True,
        capture_output=True,
        text=True,
    )

    markdown = output.read_text(encoding='utf-8')
    assert '# Firstboot release-gate handoff summary smoke check' in markdown
    assert 'Source values' in markdown
    assert 'Privacy exclusions' in markdown
    assert 'Rollback' in markdown
    assert 'raw telemetry' in markdown


def test_summary_smoke_static_packaging_service_and_docs_contracts() -> None:
    subprocess.run([sys.executable, '-m', 'py_compile', 'firstboot_release_gate_handoff_summary_smoke.py'], check=True)
    docs = Path('docs/firstboot_release_gate_handoff_summary_smoke.md').read_text(encoding='utf-8')
    changelog = Path('docs/firstboot_release_gate_handoff_summary_smoke_changelog.md').read_text(encoding='utf-8')
    service = Path('firstboot_release_gate.service').read_text(encoding='utf-8')
    build = Path('build_custom_iso.sh').read_text(encoding='utf-8')
    assert '--require-pass' in docs
    assert 'summary.env' in docs
    assert 'aggregate-only' in docs
    assert 'rollback' in docs.lower()
    assert 'firstboot_release_gate_handoff_summary_smoke.py' in changelog
    assert 'firstboot_release_gate.handoff_summary_smoke.json' in service
    assert 'firstboot_release_gate_handoff_summary_smoke.py' in build
